---
- name: Gather VsVip_Ref of VIP IP
  avi_api_session:
    avi_credentials: "{{ avi_credentials }}"
    api_version: "{{ avi_credentials.api_version }}"
    tenant: "{{ avi_credentials.tenant | default('admin') }}"
    http_method: get
    timeout: 300
    path: vsvip
    params:
      vip.contains: "{{ vsvip_ip }}"
  register: vsvip_ref

- set_fact:
    vsvip: "{{ vsvip_ref.obj.results[0] }}"

- name: Gather virtualservice UUID of vsvip
  avi_api_session:
    avi_credentials: "{{ avi_credentials }}"
    api_version: "{{ avi_credentials.api_version }}"
    tenant: "{{ avi_credentials.tenant }}"
    http_method: get
    timeout: 300
    path: virtualservice
    params:
      vsvip_ref: "{{ vsvip.uuid }}"
      cloud_ref.name: "{{ cloud_name }}"
  register: virtualservice_obj

- name: Disable virtualservice(s) with vsvip {{ vsvip.name }}
  avi_virtualservice:
    avi_credentials: "{{ avi_credentials }}"
    api_version: "{{ avi_credentials.api_version }}"
    tenant: "{{ avi_credentials.tenant }}"
    avi_api_update_method: patch
    avi_api_patch_op: replace
    name: "{{ item.name }}"
    enabled: false
  loop: "{{ virtualservice_obj.obj.results }}"
  when: item.se_group_ref != new_se_group.obj.results[0].url

- name: Update Service Engine Group from Current to New
  avi_virtualservice:
    avi_credentials: "{{ avi_credentials }}"
    api_version: "{{ avi_credentials.api_version }}"
    tenant: "{{ avi_credentials.tenant }}"
    avi_api_update_method: patch
    avi_api_patch_op: replace
    name: "{{ item.name }}"
    se_group_ref: '/api/serviceenginegroup/{{ new_se_group.obj.results[0].uuid }}'
  loop: "{{ virtualservice_obj.obj.results }}"
  when: item.se_group_ref != new_se_group.obj.results[0].url

- name: Enable virtualservice(s) with vsvip {{ vsvip.name }}
  avi_virtualservice:
    avi_credentials: "{{ avi_credentials }}"
    api_version: "{{ avi_credentials.api_version }}"
    tenant: "{{ avi_credentials.tenant }}"
    avi_api_update_method: patch
    avi_api_patch_op: replace
    name: "{{ item.name }}"
    enabled: true
  loop: "{{ virtualservice_obj.obj.results }}"