---
- name: Virtual Service Migration
  hosts: ctl
  become: no
  gather_facts: no
  connection: local
  roles:
    - role: "avinetworks.avisdk"
  vars_files:
    - vars.yml
  
  tasks:
    - name: Get API Object of current SEG
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: serviceenginegroup
        params:
          name: "{{ cur_seg }}"
          cloud_ref.name: "{{ cloud_name }}"
      register: current_se_group

    - debug: msg="{{ current_se_group }}"

    - name: Get API Object of new SEG
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: serviceenginegroup
        params:
          name: "{{ new_seg }}"
          cloud_ref.name: "{{ cloud_name }}"
      register: new_se_group

    - name: Migrate List of VSVIP
      include_role:
        name: migrate_virtualservice
      loop: "{{ vsvip_migration_list }}"
      loop_control:
        loop_var: vsvip_ip

    - debug: msg="Migration Complete!"